index:
    path: /
    controller: App\Controller\DefaultController::index

single_news:
  path: /news/{id}
  controller: App\Controller\DefaultController::showSingleNews

#Authorization
app_register:
  path: /register
  controller: App\Controller\RegistrationController::register

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
#End Authorization

#Admin-Panel
#User
admin:
  path: /admin
  controller: App\Controller\AdminController::index

admin_users:
  path: /admin/users
  controller: App\Controller\AdminController::users

admin_remove_user:
  path: /admin/removeUser/{id}
  controller: App\Controller\AdminController::removeUser

admin_edit_user:
  path: /admin/editUser/{id}
  controller: App\Controller\AdminController::editUser

admin_save_user:
  path: /admin/saveUser/{id}
  controller: App\Controller\AdminController::saveUser
#End User

#News
admin_news:
  path: /admin/news
  controller: App\Controller\AdminController::showNews
#End News
#End Admin-Panel